all:	configure

configure:	 Makefile.in configure.ac
	@aclocal
	@autoheader
	@autoconf
	@rm -rf *.cache

clean:
	@if [ -f Makefile ]; then make clean; fi
	@rm -rvf Makefile configure config.*
	@rm -rvf src/.ui_* src/.obj_* src/.moc_*
	@rm -rvf src/config.* src/*.pri src/lib*.so*
	@rm -rvf src/Makefile src/Makefile.src_* src/*.mak src/*.mak.*
	@rm -rvf *.cache *.log *.status *.spec *.mak *.m4 .m4
	@rm -rvf .qmake.stash src/.qmake.stash
